network.host: 0.0.0.0
discovery.zen.minimum_master_nodes: 1

path:
  data: /usr/share/elasticsearch/data/data
  logs: /usr/share/elasticsearch/data/log

script.engine.groovy.inline.update: on
script.inline: on
