#!/bin/bash

cd "$(dirname "$0")" || exit

cd .. || exit

sbt api/docker:publishLocal
sbt serving/docker:publishLocal

cd - || exit

docker build -t blah/flume blah-flume/
docker build -t blah/hadoop-base blah-hadoop-base/
docker build -t blah/hadoop-master blah-hadoop-master/
docker build -t blah/hadoop-slave blah-hadoop-slave/
docker build -t blah/spark-base blah-spark-base/
docker build -t blah/spark-master blah-spark-master/
docker build -t blah/spark-worker blah-spark-worker/
