#!/bin/bash

set -e

cd "$(dirname "$0")"

docker build -t blah/elasticsearch blah-elasticsearch/
docker build -t blah/flume blah-flume/
docker build -t blah/hadoop-base blah-hadoop-base/
docker build -t blah/hadoop-master blah-hadoop-master/
docker build -t blah/hadoop-slave blah-hadoop-slave/
docker build -t blah/mesos-dns blah-mesos-dns/
docker build -t blah/spark-mesos blah-spark-mesos/

cd ..

sbt api/docker:publishLocal
sbt serving/docker:publishLocal
sbt algo/assembly
sbt algo/docker:publishLocal
