#!/bin/bash

ZK=${ZOOKEEPER_URL:-"zk://localhost:2181/mesos"}
RES=${RESOLVERS:-"8.8.8.8"}
RES=$(echo "$RES" | sed -e 's#[^,][^,]*#"&"#g')

sed -i s#ZOOKEEPER_URL#${ZK}# /config.json
sed -i s#RESOLVERS#${RES}# /config.json

/mesos-dns -config=/config.json
