ui: tape
concurrency: 5
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: microsoftedge
    version: latest
  - name: ie
    version: 10..latest
  - name: iphone
    version: latest
  - name: ipad
    version: latest
  - name: android
    version: latest
browserify:
  - transform:
      name: babelify
      presets: es2015
